### ISSUE TITLE
scelta parametri

### ISSUE THREAD

**Issue by davide-202** [davide-202/sega_circolare#1]
@DavidLeoni al punto 1.4 ha scritto che per la creazione del componente si devono scegliere minimo 3 parametri correlati tra loro. Per cui potrei attaccare la ruota a un sostegno, può andare bene?

**Comment by DavidLeoni** [comment]
L'importante è che sia possibile testare dei vincoli non banali, se metti il sostegno puoi confrontarlo col raggio che è sicuramente un miglioramento

**Comment by davide-202** [comment]
grazie mille
